### PR TITLE
Allow latest `psr/*` dependencies

### PR DESCRIPTION
**Pull request by geerteltink**
This PR allow latest psr dependencies.

### CODE REVIEW

**Comment by geerteltink** [comment]
@lcobucci do you have an idea why this is failing for php 8.0 with lowest dependencies only?

```
1) MezzioTest\Authentication\OAuth2\Pdo\OAuth2PdoMiddlewareTest::testProcessClientCredentialGrantConfidential
Lcobucci\JWT\Signer\InvalidKeyProvided: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line
```

**Comment by lcobucci** [comment]
> @lcobucci do you have an idea why this is failing for php 8.0 with lowest dependencies only?
> 
> ```
> 1) MezzioTest\Authentication\OAuth2\Pdo\OAuth2PdoMiddlewareTest::testProcessClientCredentialGrantConfidential
> Lcobucci\JWT\Signer\InvalidKeyProvided: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line
> ```

I'll have a look. OpenSSL usually gives that error when the key is empty or something like that.

I also see that composer is installing v3.4.6 when running PHP 8.0, which shouldn't be possible as it isn't compatible with that version: https://packagist.org/packages/lcobucci/jwt#3.4.6

**Comment by geerteltink** [comment]
Interesting:

```
Received job: {"command":"./vendor/bin/phpunit","php":"8.0","extensions":["pdo-sqlite"],"ini":["memory_limit        = -1"],"dependencies":"lowest","ignore_platform_reqs_8":true,"ignore_php_platform_requirement":true,"additional_composer_arguments":[]}
```

Where is that config coming from?

**Comment by Ocramius** [comment]
@froschdesign do we need to fix markdownlint before merging here? Seems like it wasn't run at all before :thinking:

**Comment by geerteltink** [comment]
@Ocramius It has to be fixed anyway. I'll try to do it today.

**Review by Ocramius — APPROVED** [review]
Thanks @geerteltink!

**Pull request merged**
