### PR TITLE
Apply PHP 7.4 syntax and typed property

### PR DESCRIPTION
**Pull request by samsonasik**
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Since composer.json require php 7.4, php 7.4 syntax can be applied with typed properties. 

- For `final class`, typed properties for protected is allowed if no inherit of parent or used by its final class parent.
- For `final class`, typed properties for protected can be changed to `private` if not used in parent or exists in parent class.
- Otherwise, update only private properties.

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
Thanks @samsonasik!

**Review by Ocramius — CHANGES_REQUESTED** [review]
Wait, loads of failures:

```

There were 5 errors:

1) MezzioTest\Authentication\OAuth2\Repository\Pdo\AccessTokenRepositoryFactoryTest::testFactory
TypeError: Typed property MezzioTest\Authentication\OAuth2\Repository\Pdo\AccessTokenRepositoryFactoryTest::$container must be an instance of Psr\Container\ContainerInterface, Prophecy\Prophecy\ObjectProphecy used

/github/workspace/test/Repository/Pdo/AccessTokenRepositoryFactoryTest.php:22
phpvfscomposer:///github/workspace/vendor/phpunit/phpunit/phpunit:97

2) MezzioTest\Authentication\OAuth2\Repository\Pdo\AuthCodeRepositoryFactoryTest::testFactory
TypeError: Typed property MezzioTest\Authentication\OAuth2\Repository\Pdo\AuthCodeRepositoryFactoryTest::$container must be an instance of Psr\Container\ContainerInterface, Prophecy\Prophecy\ObjectProphecy used

/github/workspace/test/Repository/Pdo/AuthCodeRepositoryFactoryTest.php:22
phpvfscomposer:///github/workspace/vendor/phpunit/phpunit/phpunit:97

3) MezzioTest\Authentication\OAuth2\Repository\Pdo\ClientRepositoryFactoryTest::testFactory
TypeError: Typed property MezzioTest\Authentication\OAuth2\Repository\Pdo\ClientRepositoryFactoryTest::$container must be an instance of Psr\Container\ContainerInterface, Prophecy\Prophecy\ObjectProphecy used

/github/workspace/test/Repository/Pdo/ClientRepositoryFactoryTest.php:22
phpvfscomposer:///github/workspace/vendor/phpunit/phpunit/phpunit:97

4) MezzioTest\Authentication\OAuth2\Repository\Pdo\RefreshTokenRepositoryFactoryTest::testFactory
TypeError: Typed property MezzioTest\Authentication\OAuth2\Repository\Pdo\RefreshTokenRepositoryFactoryTest::$container must be an instance of Psr\Container\ContainerInterface, Prophecy\Prophecy\ObjectProphecy used

/github/workspace/test/Repository/Pdo/RefreshTokenRepositoryFactoryTest.php:22
phpvfscomposer:///github/workspace/vendor/phpunit/phpunit/phpunit:97

5) MezzioTest\Authentication\OAuth2\Repository\Pdo\ScopeRepositoryFactoryTest::testFactory
TypeError: Typed property MezzioTest\Authentication\OAuth2\Repository\Pdo\ScopeRepositoryFactoryTest::$container must be an instance of Psr\Container\ContainerInterface, Prophecy\Prophecy\ObjectProphecy used

/github/workspace/test/Repository/Pdo/ScopeRepositoryFactoryTest.php:22
phpvfscomposer:///github/workspace/vendor/phpunit/phpunit/phpunit:97
```

I think we may need to remove prophecy as part of our refactoring work

**Comment by samsonasik** [comment]
@Ocramius it should be fixed now.

**Comment by Ocramius** [comment]
Nope 🤔

**Comment by samsonasik** [comment]
Let's try again

**Comment by samsonasik** [comment]
@Ocramius All green 🎉

**Review by Ocramius — APPROVED** [review]
Thanks @samsonasik!

**Pull request merged**
