### PR TITLE
PHP 8 Support

### LINKED ISSUE #14: Investigate test failure with league/oauth2-server 8.1.0
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.0.2

#### Summary

[`league/oauth2-server` 8.1.0](https://github.com/thephpleague/oauth2-server/tree/8.1.0) has been released and we are getting one failure in our tests:

```
There was 1 failure:

1) MezzioTest\Authentication\OAuth2\Pdo\OAuth2PdoMiddlewareTest::testProcessClientCredentialGrant
Failed asserting that 401 matches expected 200.

/home/travis/build/mezzio/mezzio-authentication-oauth2/test/Pdo/OAuth2PdoMiddlewareTest.php:192
```

We need to investigate why this test is failing and fix it accordingly.
If the issue is with new release of oauth2-server we need create issue there and link it here.

### LINKED ISSUE #23: PHP 8.0 support
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

To be prepared for the december release of PHP 8.0, this repository has some additional TODOs to be tested against the new major version.

In order to make this repository compatible, one has to follow these steps:

- [x] Modify `composer.json` to provide support for PHP 8.0 by adding the constraint `~8.0.0`
- [x] Modify `composer.json` to drop support for PHP less than 7.3
- [x] Modify `composer.json` to implement phpunit 9.3 which supports PHP 7.3+
- [x] Modify `.travis.yml` to ignore platform requirements when installing composer dependencies (simply add `--ignore-platform-reqs` to `COMPOSER_ARGS` env variable)
- [x] Modify `.travis.yml` to add PHP 8.0 to the matrix (*NOTE*: Do not allow failures as PHP 8.0 has a feature freeze since 2020-08-04!)
- [x] Modify source code in case there are incompatibilities with PHP 8.0

### PR DESCRIPTION
**Pull request by agustingomes**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

This PR intends to add support for PHP 8 and solve https://github.com/mezzio/mezzio-authentication-oauth2/issues/23

Fixes #23

### CODE REVIEW

**Comment by adambalint-srg** [comment]
@agustingomes 
Waiting for this merge, but I've one more suggestion, in the generate-oauth2-keys command. 
In PHP8 resources are objects (https://php.watch/versions/8.0/OpenSSL-resource), so it should support this.

Instead of this:
```php
if (!(is_resource($res)) {
    fwrite(STDERR, 'Failed to create private key.' . PHP_EOL);
    fwrite(STDERR, 'Check your openssl extension settings.' . PHP_EOL);
    exit(1);
}
```

It should check for objects
```php
if (!(is_resource($res) || (is_object($res) && $res instanceof OpenSSLAsymmetricKey))) {
    fwrite(STDERR, 'Failed to create private key.' . PHP_EOL);
    fwrite(STDERR, 'Check your openssl extension settings.' . PHP_EOL);
    exit(1);
}
```

Could you add this to this PR?

**Review by Ocramius — APPROVED** [review]
Excellent, thanks @agustingomes!

**Comment by agustingomes** [comment]
@adambalint-srg it's probably better to introduce it as a separate PR, since I only changed what was needed for PHP 8 compatibility.

**Comment by adambalint-srg** [comment]
@agustingomes Yes, I'll do it soon

**Pull request merged**
