### PR TITLE
Drop `laminas/laminas-zendframework-bridge` and `zendframework/*` compatibility

### PR DESCRIPTION
**Pull request by PowerKiKi**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Increase performance by removing a compatibility layer while **not** introducing breaking changes.

This follow the process described in details in:

https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2021-08-02-TSC-Minutes.md#remove-laminaslaminas-zendframework-bridge-dependency-from-our-packages

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
CI seems to be completely borked here: can't merge ATM

**Comment by PowerKiKi** [comment]
CI should be unborked, and hopefully even green.

... if only GitHub Actions trusted me a little bit more... have you considered the following settings for Laminas ? I feel it would save time to both contributors and maintainers while still preventing the worse of abuses ?

image

**Comment by froschdesign** [comment]
@PowerKiKi 
@Ocramius means this: https://github.com/mezzio/mezzio-authentication-oauth2/runs/4425358718?check_suite_focus=true#step:3:19

**Comment by froschdesign** [comment]
@PowerKiKi 
Now it looks better!

**Comment by PowerKiKi** [comment]
Unfortunately this package has too many broken tests, and that have been broken for a while (at least since https://github.com/mezzio/mezzio-authentication-oauth2/pull/34). And since I never used this package at all, I won't be able to invest more time in this.

Feel free to reject this PR, or finish it, whichever feels the most appropriate to you.

**Comment by Ocramius** [comment]
Handled in #41, thanks @PowerKiKi!

**Pull request closed without merging**
